### ISSUE TITLE
Switch from Joda to java.time

### ISSUE THREAD

**Issue by ylaurent** [Deliganli/binance4s#1]
Hello,
Thanks for the great lib, looks pretty dope :)
Any particular reason to use Joda instead of java.time now ? I thought since the release of java 8 java.time should be to go to.
I can do a MR if you think its worth switching!

**Comment by Deliganli** [comment]
thanks a lot :)
I am using joda time usually in everything but I guess what you offer makes sense in terms of removing a needless dependency. If you would like to submit a PR I am more than happy to include

**Comment by ylaurent** [comment]
Nice I just did it! hopefully I didn't mess anything!
